[project]
name = "pyhammer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.4",
    "ruff>=0.9.7",
]

[tool.ruff]
indent-width=4
line-length=120

[tool.ruff.lint]
select=["E","F","N", "B"]
